---
title: "DataPulling"
output: html_document
date: "2025-06-02"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

##Installing Packages to connect MySql to R
```{r}
install.packages("RMySQL")
install.packages("RMariaDB")
library(RMySQL)
library(RMariaDB)
library(tidyr)
library(ggplot2)
library(reshape2)
```
#Connecting MySql to DB
```{r}
mysqlconnection = dbConnect(RMySQL:: MySQL(),
                            dbname = 'Football',
                            host = 'localhost',
                            port = 3306,
                            user = 'Lromes',
                            password = '1234!')
```

##Listing the tables in DB
```{r}
dbListTables(mysqlconnection)
```




##Writing Queries
```{r}

df_ko <- dbGetQuery(mysqlconnection, "SELECT * FROM kickoff")
print(df_ko)

df_punt <- dbGetQuery(mysqlconnection, "SELECT * From Punt")
print(df_punt)

df_conditions <- dbGetQuery(mysqlconnection, "Describe Conditions")
```
```{r}
df_data <- dbGetQuery(mysqlconnection, "SELECT P.PuntID, P.PlayerIDP, P.PLocID, P.PlayerIDLS, P.SnapLocID, P.PDate, P.Snaptime, P.OP,                                         P.H2F, P.Hang, P.Distance, P.Efficiency, 
                                        PL.Height, PL.Weight,
                                        C.Practice, C.Game, C.precipitation, C.Wind, C.Grass, C.Turf, C.Temp
                                        
                                        FROM Player PL
                                        
                                        JOIN Punt P ON PL.PlayerID = P.PlayerIDP
                                        JOIN Conditions C ON P.PDATE = C.DATE
                          ")
```
```{r}
dim(df_data)
View(df_data)
write.csv(df_data, "~/Desktop/Personal/Football ML.csv", row.names = FALSE)

```


##Replacing Date with Number for normalization
```{r}
df_data$PDate <- as.numeric(as.Date(df_data$PDate))
df_data <- df_data[, -1]
dim(df_data)
```

##Normalizing Data
```{r}
columns <- c(5,6,7,8,9,10,12,13,16,17,20)
df_norm <- df_data
df_norm[columns] <- scale(df_data[columns])
head(df_norm)
view(df_norm)
```

##Missing Value Imputation and Comparison Before and After
```{r}
sum(is.na(df_norm))
colSums(is.na(df_norm))
df_before <- df_norm
impute_median <- function(x){
  x[is.na(x)] <-median(x, na.rm = TRUE)
  return(x)
}
df_after <- as.data.frame(lapply(df_norm, impute_median))



##Plotting

# Select numeric columns only
numeric_cols <- sapply(df_norm, is.numeric)

# Prepare data for plotting density before and after imputation
plot_data_before <- melt(df_before[, numeric_cols])
plot_data_after <- melt(df_after[, numeric_cols])

plot_data_before$Type <- "Before Imputation"
plot_data_after$Type <- "After Imputation"

plot_data <- rbind(plot_data_before, plot_data_after)

ggplot(plot_data, aes(x = value, color = Type)) +
  geom_density() +
  facet_wrap(~variable, scales = "free") +
  labs(title = "Density Plot Before and After Median Imputation",
       x = "Value",
       y = "Density") +
  theme_minimal()

```

```{r}
write.csv(df_norm, "~/Desktop/Personal/Football ML.csv", row.names = FALSE)
```

